name: movie_admin
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

# flutter packages pub run build_runner build --delete-conflicting-outputs
# (\w+):(\s+)([a-zA-Z\s\[\]|]+);
# $3 get $1;

dependencies:
  qr_code_scanner: ^0.7.0
  charts_flutter: ^0.12.0
  uuid: ^3.0.6
  firebase_core: ^1.16.0
  octo_image: ^1.0.0
  flutter_slidable: ^0.5.7
  url_launcher: ^6.1.0
  expandable: ^4.1.4
  built_collection: ^5.0.0
  loading_indicator: ^1.2.0
  google_sign_in: ^4.5.6
  font_awesome_flutter: ^8.10.0
  image_picker: ^0.8.5
  cached_network_image: ^3.2.0
  firebase_storage: ^10.2.5
  flutter_dotenv: ^2.1.0
  datetime_picker_formfield: ^1.0.0
  intl: ^0.17.0
  tuple: ^1.0.3
  path: ^1.8.0
  http: ^0.13.1
  firebase_auth: ^3.3.15
  built_value: ^8.1.0
  shared_preferences: ^2.0.13
  clock: ^1.1.0
  rxdart: ^0.26.0
  rx_redux: ^2.2.0-nullsafety.2
  distinct_value_connectable_stream: ^1.2.0-nullsafety.5
  flutter_provider: ^2.0.0
  rx_shared_preferences: ^2.0.0-nullsafety.0
  disposebag: ^1.5.0-nullsafety.1
  flutter_disposebag: ^1.1.0-nullsafety.1
  flutter_bloc_pattern: ^2.0.0-nullsafety.1
  rxdart_ext: ^0.0.1
  listenable_stream: ^1.0.0-nullsafety.1
  stream_loader: ^1.1.0-nullsafety.2
  flutter_google_places: ^0.3.0
  path_provider: ^2.0.9
  meta: ^1.7.0
  analyzer: ^2.8.0

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  build_runner: 2.1.6
  built_value_generator: ^8.2.3
  pedantic: ^1.9.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic

        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic

        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-LightItalic.ttf
          weight: 300
          style: italic

        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Italic.ttf
          weight: 400
          style: italic

        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic

        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic

        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic

